"""Cricsheet historical data loader and parser."""

import os
from pathlib import Path

import pandas as pd


DATA_DIR = Path(os.getenv("CRICSHEET_DATA_DIR", "data/cricsheet"))


def load_match_data(match_type: str = "t20s") -> pd.DataFrame:
    """
    Load Cricsheet match-level data.

    Args:
        match_type: One of 't20s', 'odis', 'tests', 'ipl'

    Returns:
        DataFrame with columns: match_id, date, team1, team2, winner, venue, toss_winner, toss_decision
    """
    filepath = DATA_DIR / f"{match_type}_matches.csv"
    if not filepath.exists():
        raise FileNotFoundError(f"Cricsheet data not found at {filepath}")

    df = pd.read_csv(filepath, parse_dates=["date"])
    return df


def load_ball_by_ball(match_type: str = "t20s") -> pd.DataFrame:
    """
    Load Cricsheet ball-by-ball data for detailed analysis.

    Args:
        match_type: One of 't20s', 'odis', 'tests', 'ipl'

    Returns:
        DataFrame with delivery-level data
    """
    filepath = DATA_DIR / f"{match_type}_deliveries.csv"
    if not filepath.exists():
        raise FileNotFoundError(f"Cricsheet data not found at {filepath}")

    df = pd.read_csv(filepath)
    return df


def load_player_data(match_type: str = "t20s") -> pd.DataFrame:
    """Load Cricsheet player appearance data generated by fetch_cricsheet.py."""
    filepath = DATA_DIR / f"{match_type}_players.csv"
    if not filepath.exists():
        raise FileNotFoundError(f"Cricsheet player data not found at {filepath}")

    return pd.read_csv(filepath, parse_dates=["date"])


def infer_team_gender(team: str) -> str:
    return "female" if "Women" in team else "male"


def normalize_team_name(team: str) -> str:
    return team.replace(" Women", "").replace(" Men", "").strip()


def get_recent_player_pool(team: str, match_type: str = "t20s", n_matches: int = 12, max_players: int = 18) -> list[str]:
    """Return players who appeared recently for a team in Cricsheet data."""
    df = load_player_data(match_type)
    team_name = normalize_team_name(team)
    team_rows = df[df["team"] == team_name]
    if "gender" in team_rows.columns:
        team_rows = team_rows[team_rows["gender"] == infer_team_gender(team)]
    team_rows = team_rows.sort_values("date")
    if team_rows.empty:
        return []

    recent_match_ids = team_rows["match_id"].drop_duplicates().tail(n_matches)
    recent_rows = team_rows[team_rows["match_id"].isin(recent_match_ids)]
    player_counts = recent_rows.groupby("player").size().sort_values(ascending=False)
    return player_counts.head(max_players).index.tolist()


def team_match_filter(df: pd.DataFrame, team: str) -> pd.Series:
    """Build a team/gender-aware filter for Cricsheet match rows."""
    team_name = normalize_team_name(team)
    team_matches = (df["team1"] == team_name) | (df["team2"] == team_name)
    if "gender" in df.columns:
        team_matches = team_matches & (df["gender"] == infer_team_gender(team))
    return team_matches


def get_team_recent_form(team: str, match_type: str = "t20s", n_matches: int = 10) -> dict:
    """
    Get team's recent form statistics.

    Args:
        team: Team name
        match_type: Match format
        n_matches: Number of recent matches to consider

    Returns:
        Dict with win_rate, avg_score, avg_wickets_lost
    """
    df = load_match_data(match_type)
    team_name = normalize_team_name(team)
    team_matches = df[team_match_filter(df, team)].tail(n_matches)

    if team_matches.empty:
        return {"win_rate": 0.5, "matches_played": 0, "avg_score": 0, "form_last_10": []}

    form_last_10 = ["W" if winner == team_name else "L" for winner in team_matches["winner"]]
    wins = form_last_10.count("W")
    total = len(team_matches)

    return {
        "win_rate": wins / total if total > 0 else 0.5,
        "matches_played": total,
        "recent_wins": int(wins),
        "form_last_10": form_last_10,
    }


def get_venue_stats(venue: str, match_type: str = "t20s") -> dict:
    """
    Get venue-specific statistics.

    Args:
        venue: Venue name
        match_type: Match format

    Returns:
        Dict with avg_first_innings_score, toss_bat_first_win_rate
    """
    df = load_match_data(match_type)
    venue_matches = df[df["venue"].str.contains(venue, case=False, na=False)]

    if venue_matches.empty:
        return {"matches_at_venue": 0, "avg_first_innings_score": 160}

    bat_first_wins = venue_matches[
        (venue_matches["toss_decision"] == "bat") &
        (venue_matches["toss_winner"] == venue_matches["winner"])
    ]

    return {
        "matches_at_venue": len(venue_matches),
        "toss_bat_first_win_rate": len(bat_first_wins) / len(venue_matches) if len(venue_matches) > 0 else 0.5,
    }


def get_head_to_head(team1: str, team2: str, match_type: str = "t20s") -> dict:
    """
    Get head-to-head record between two teams.

    Args:
        team1: First team name
        team2: Second team name
        match_type: Match format

    Returns:
        Dict with total_matches, team1_wins, team2_wins
    """
    df = load_match_data(match_type)
    h2h = df[
        ((df["team1"] == team1) & (df["team2"] == team2)) |
        ((df["team1"] == team2) & (df["team2"] == team1))
    ]

    if h2h.empty:
        return {"total_matches": 0, "team1_wins": 0, "team2_wins": 0}

    return {
        "total_matches": len(h2h),
        "team1_wins": int((h2h["winner"] == team1).sum()),
        "team2_wins": int((h2h["winner"] == team2).sum()),
    }
