"""Cricsheet historical data loader and parser."""

import os
from pathlib import Path

import pandas as pd


DATA_DIR = Path(os.getenv("CRICSHEET_DATA_DIR", "data/cricsheet"))


def load_match_data(match_type: str = "t20s") -> pd.DataFrame:
    """
    Load Cricsheet match-level data.

    Args:
        match_type: One of 't20s', 'odis', 'tests', 'ipl'

    Returns:
        DataFrame with columns: match_id, date, team1, team2, winner, venue, toss_winner, toss_decision
    """
    filepath = DATA_DIR / f"{match_type}_matches.csv"
    if not filepath.exists():
        raise FileNotFoundError(f"Cricsheet data not found at {filepath}")

    df = pd.read_csv(filepath, parse_dates=["date"])
    return df


def load_ball_by_ball(match_type: str = "t20s") -> pd.DataFrame:
    """
    Load Cricsheet ball-by-ball data for detailed analysis.

    Args:
        match_type: One of 't20s', 'odis', 'tests', 'ipl'

    Returns:
        DataFrame with delivery-level data
    """
    filepath = DATA_DIR / f"{match_type}_deliveries.csv"
    if not filepath.exists():
        raise FileNotFoundError(f"Cricsheet data not found at {filepath}")

    df = pd.read_csv(filepath)
    return df


def load_player_data(match_type: str = "t20s") -> pd.DataFrame:
    """Load Cricsheet player appearance data generated by fetch_cricsheet.py."""
    filepath = DATA_DIR / f"{match_type}_players.csv"
    if not filepath.exists():
        raise FileNotFoundError(f"Cricsheet player data not found at {filepath}")

    return pd.read_csv(filepath, parse_dates=["date"])


def infer_team_gender(team: str) -> str:
    return "female" if "Women" in team else "male"


def normalize_team_name(team: str) -> str:
    return team.replace(" Women", "").replace(" Men", "").strip()


def get_recent_player_pool(team: str, match_type: str = "t20s", n_matches: int = 12, max_players: int = 18) -> list[str]:
    """Return players who appeared recently for a team in Cricsheet data."""
    df = load_player_data(match_type)
    team_name = normalize_team_name(team)
    team_rows = df[df["team"] == team_name]
    if "gender" in team_rows.columns:
        team_rows = team_rows[team_rows["gender"] == infer_team_gender(team)]
    team_rows = team_rows.sort_values("date")
    if team_rows.empty:
        return []

    recent_match_ids = team_rows["match_id"].drop_duplicates().tail(n_matches)
    recent_rows = team_rows[team_rows["match_id"].isin(recent_match_ids)]
    player_counts = recent_rows.groupby("player").size().sort_values(ascending=False)
    return player_counts.head(max_players).index.tolist()


def team_match_filter(df: pd.DataFrame, team: str) -> pd.Series:
    """Build a team/gender-aware filter for Cricsheet match rows."""
    team_name = normalize_team_name(team)
    team_matches = (df["team1"] == team_name) | (df["team2"] == team_name)
    if "gender" in df.columns:
        team_matches = team_matches & (df["gender"] == infer_team_gender(team))
    return team_matches


def get_team_recent_form(team: str, match_type: str = "t20s", n_matches: int = 10) -> dict:
    """
    Get team's recent form statistics.

    Args:
        team: Team name
        match_type: Match format
        n_matches: Number of recent matches to consider

    Returns:
        Dict with win_rate, avg_score, avg_wickets_lost
    """
    df = load_match_data(match_type)
    team_name = normalize_team_name(team)
    team_matches = df[team_match_filter(df, team)].tail(n_matches)

    if team_matches.empty:
        return {"win_rate": 0.5, "matches_played": 0, "avg_score": 0, "form_last_10": []}

    form_last_10 = ["W" if winner == team_name else "L" for winner in team_matches["winner"]]
    wins = form_last_10.count("W")
    total = len(team_matches)

    return {
        "win_rate": wins / total if total > 0 else 0.5,
        "matches_played": total,
        "recent_wins": int(wins),
        "form_last_10": form_last_10,
    }


def get_venue_stats(venue: str, match_type: str = "t20s") -> dict:
    """
    Get venue-specific statistics.

    Args:
        venue: Venue name
        match_type: Match format

    Returns:
        Dict with avg_first_innings_score, toss_bat_first_win_rate
    """
    df = load_match_data(match_type)
    venue_matches = df[df["venue"].str.contains(venue, case=False, na=False)]

    if venue_matches.empty:
        return {"matches_at_venue": 0, "avg_first_innings_score": 160}

    bat_first_wins = venue_matches[
        (venue_matches["toss_decision"] == "bat") &
        (venue_matches["toss_winner"] == venue_matches["winner"])
    ]

    return {
        "matches_at_venue": len(venue_matches),
        "toss_bat_first_win_rate": len(bat_first_wins) / len(venue_matches) if len(venue_matches) > 0 else 0.5,
    }


def get_head_to_head(team1: str, team2: str, match_type: str = "t20s") -> dict:
    """
    Get head-to-head record between two teams.

    Args:
        team1: First team name
        team2: Second team name
        match_type: Match format

    Returns:
        Dict with total_matches, team1_wins, team2_wins
    """
    df = load_match_data(match_type)
    h2h = df[
        ((df["team1"] == team1) & (df["team2"] == team2)) |
        ((df["team1"] == team2) & (df["team2"] == team1))
    ]

    if h2h.empty:
        return {"total_matches": 0, "team1_wins": 0, "team2_wins": 0}

    return {
        "total_matches": len(h2h),
        "team1_wins": int((h2h["winner"] == team1).sum()),
        "team2_wins": int((h2h["winner"] == team2).sum()),
    }


def load_delivery_data(match_type: str = "t20s") -> pd.DataFrame:
    """Load Cricsheet ball-by-ball delivery data.

    Columns: match_id, date, batter, bowler, runs_batter, is_boundary, is_wicket, wicket_batter
    """
    filepath = DATA_DIR / f"{match_type}_deliveries.csv"
    if not filepath.exists():
        raise FileNotFoundError(f"Cricsheet delivery data not found at {filepath}. Run fetch_cricsheet.py first.")
    return pd.read_csv(filepath)


def get_player_recent_batting_scores(
    player_name: str,
    match_type: str = "t20s",
    n: int = 5,
) -> list[int]:
    """Return the last N innings scores for a batter, oldest → newest.

    Computes per-match run totals from ball-by-ball data so each entry
    represents one innings, not one ball.
    """
    try:
        df = load_delivery_data(match_type)
    except FileNotFoundError:
        return []

    batter_df = df[df["batter"].str.lower() == player_name.lower()].copy()
    if batter_df.empty:
        return []

    # Sum runs per match_id → one score per innings appearance
    scores_by_match = (
        batter_df.groupby(["match_id", "date"])["runs_batter"]
        .sum()
        .reset_index()
        .sort_values("date")
    )
    return [int(r) for r in scores_by_match["runs_batter"].tail(n)]


def get_player_recent_bowling_figures(
    player_name: str,
    match_type: str = "t20s",
    n: int = 5,
) -> list[int]:
    """Return the last N wicket tallies for a bowler, oldest → newest."""
    try:
        df = load_delivery_data(match_type)
    except FileNotFoundError:
        return []

    bowler_df = df[df["bowler"].str.lower() == player_name.lower()].copy()
    if bowler_df.empty:
        return []

    # A wicket is credited to the bowler when wicket_batter matches the batter
    # (i.e. not run-outs where the fielder gets credit)
    bowler_df["bowler_wicket"] = (
        bowler_df["is_wicket"]
        & (bowler_df["wicket_batter"] == bowler_df["batter"])
    )
    wickets_by_match = (
        bowler_df.groupby(["match_id", "date"])["bowler_wicket"]
        .sum()
        .reset_index()
        .sort_values("date")
    )
    return [int(w) for w in wickets_by_match["bowler_wicket"].tail(n)]


def get_player_h2h_stats(
    batter: str,
    bowler: str,
    match_type: str = "t20s",
) -> dict:
    """Compute head-to-head stats between a specific batter and bowler.

    Returns:
        {
            dismissals: int,
            balls_faced: int,
            runs_scored: int,
            dot_pct: float,        # 0-100
            boundary_pct: float,   # 0-100
            last_5: list['W' | 'NW'],  # 5 most-recent match outcomes
        }
        Empty dict if no data found.
    """
    try:
        df = load_delivery_data(match_type)
    except FileNotFoundError:
        return {}

    matchup = df[
        (df["batter"].str.lower() == batter.lower())
        & (df["bowler"].str.lower() == bowler.lower())
    ].copy()

    if matchup.empty:
        return {}

    balls_faced = len(matchup)
    runs_scored = int(matchup["runs_batter"].sum())
    dot_balls = int((matchup["runs_batter"] == 0).sum())
    boundaries = int(matchup["is_boundary"].sum())

    # Dismissals: wicket where dismissed player is this batter
    dismissals_df = matchup[matchup["is_wicket"] & (matchup["wicket_batter"] == matchup["batter"])]
    dismissals = len(dismissals_df)

    # last_5: one result per match, ordered by date
    per_match = (
        matchup.groupby(["match_id", "date"])
        .agg(
            match_wickets=("is_wicket", "sum"),
            match_wicket_batters=("wicket_batter", lambda x: (x == batter).any()),
        )
        .reset_index()
        .sort_values("date")
    )
    # W = bowler dismissed this batter in that match
    outcomes = ["W" if row["match_wicket_batters"] else "NW" for _, row in per_match.iterrows()]
    last_5 = outcomes[-5:]

    return {
        "dismissals": dismissals,
        "balls_faced": balls_faced,
        "runs_scored": runs_scored,
        "dot_pct": round(dot_balls / balls_faced * 100, 1) if balls_faced else 0,
        "boundary_pct": round(boundaries / balls_faced * 100, 1) if balls_faced else 0,
        "last_5": last_5,
    }
